name: CastleClash
version: 0.2
description: By awesomephones
main: net.net76.joedevelopment.Mainplugin
commands:
  addshopblock:
    description: Admin command, adds a shop block
    usage: /addshopblock
    permission: castleclash.addshopblock
  removeshopblock:
    description: Admin command, removes a shop block
    usage: /removeshopblock
    permission: castleclash.removeshopblock
  removeallshops:
    description: Admin command, removes all shop blocks
    usage: /removeallshops
    permission: castleclash.removeallshops
  setteamspawn:
    description: Admin command, sets a team spawn
    usage: /setteamspawn <team ID>
    permission: castleclash.setteamspawn
  nogame:
    description: Admin command, cancels the current game
    usage: /nogame
    permission: castleclash.nogame
  spawnoverride:
    description: Overrides the /spawn limitation
    usage: /spawnoverride
    permission: castleclash.spawnoverride